change styleName to className in Link component
open-ch/pyrene pull request #82
Opened 2021-04-30 14:47 UTC by sanmiawi

2021-05-10 11:15 UTC, Sakai-san requested changes

2021-05-10 11:15 UTC, Sakai-san commented on pyrene/src/components/Link/Link.jsx
> +    className={clsx(styles.link, { [styles[`type-${props.type}`]]: true }, { [styles.disabled]: props.disabled })}
Please do the following when the `class` will be added anyway, means always `true`.

```
className={clsx(styles.link, styles[`type-${props.type}`], { [styles.disabled]: props.disabled })}
```

2021-05-11 08:05 UTC, Sakai-san approved these changes

2021-05-11 08:41 UTC, justmejulian approved these changes

2021-05-11 09:08 UTC, merged